# The Site Configuration

# Import the theme
theme: jekyll-theme-chirpy

# The language of the webpage
lang: pt-BR

# Change to your timezone
timezone: America/Sao_Paulo

# jekyll-seo-tag settings
title: Tukano Blog # the main title
tagline: Notícias, tutoriais, artigos e muita informação! # it will display as the subtitle
description: >- # used by seo meta and the atom feed
  Blog da Tukano com notícias, tutoriais e artigos sobre elétrica industrial e automação

avatar: "https://tukano.net/tukano.png" # ajuste o caminho conforme necessário

# Fill in the protocol & hostname for your site.
url: "https://tknsys.github.io"
# URL do blog
baseurl: "https://tknsys.github.io/blog"

github:
  username: tknsys # change to your GitHub username

social:
  name: tukano.industrial
  email: contato@tukano.net
  links:
    - https://instagram.com/tukano.industrial
    - https://www.linkedin.com/in/tukano

# Site Verification Settings
webmaster_verifications:
  google:
  bing:
  alexa:
  yandex:
  baidu:
  facebook:

# Web Analytics Settings
analytics:
  google:
    id: # fill in your Google Analytics ID
  goatcounter:
    id: # fill in your GoatCounter ID
  umami:
    id: # fill in your Umami ID
    domain: # fill in your Umami domain
  matomo:
    id: # fill in your Matomo ID
    domain: # fill in your Matomo domain
  cloudflare:
    id: # fill in your Cloudflare Web Analytics token
  fathom:
    id: # fill in your Fathom Site ID

# Page views settings
pageviews:
  provider: # now only supports 'goatcounter'

# Prefer color scheme setting.
theme_mode: # [light | dark]

# The CDN endpoint for media resources.
#cdn: "https://chirpy-img.netlify.app"

# Avatar on sidebar
#avatar: "/c

