source "https://rubygems.org"

gem "jekyll", "~> 4.2"
gem "jekyll-theme-chirpy"
gem "jekyll-feed"
gem "html-proofer", "~> 4.3.0"

platforms :mingw, :x64_mingw, :mswin, :jruby do
  gem "tzinfo", ">= 1", "< 3"
  gem "tzinfo-data"
end

gem "wdm", "~> 0.1.1", platforms: [:mingw, :x64_mingw]
